name: makinprrovider
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Network & Backend
  http: ^1.1.0
  appwrite: ^17.0.2
  dart_appwrite: ^13.0.0


  # State Management
  flutter_bloc: ^8.1.3

  # Form validation
  formz: ^0.6.1

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # Routing
  go_router: ^14.1.4

  # Icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/makinlogo.png