name: appwrite_admin_setup
description: Standalone Dart script to setup Appwrite database and collections
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dart_appwrite: ^16.1.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
